---
#TODO - remove duplicates - probably...

###############################
######             USERS  STUFF              #####
###############################

bbvps_users:
  main_user:
    name: blackfell
    group: blackfell
    shell: /bin/zsh
    create_home: true
    update_password: on_create
    groups: wheel,users,audio,storage,{{bb_group}}
    append: yes
    # FAKE PASSWORDS!!! Create with
    # python -c 'import crypt; print(crypt.crypt("PLAINTEXT PASSWORD", crypt.mksalt()))'
    password: $6$aTMFR2o2W43LY3SQ$JG0W7WMR9zTMX1yBrwOhlkHoH7EAxMlPlc.0se3c0lcNGQN6IivBBeq4J8nK6Eyt6UHLuprFoA/1Jh5rxj9s61
    ssh_key_name: /home/hullet/.ssh/linode@blackfell.net.pub
  ansible_user:
    name: myansible
    group: ansible
    shell: /bin/bash
    create_home: true
    update_password: on_create
    groups: wheel,users,audio,storage
    append: yes
    #FAKE PASSWORDS!!! Create with
    # python -c 'import crypt; print(crypt.crypt("PLAINTEXT PASSWORD", crypt.mksalt()))'
    password: $6$aTMFR2o2W43LY3SQ$JG0W7WMR9zTMX1yBrwOhlkHoH7EAxMlPlc.0se3c0lcNGQN6IivBBeq4J8nK6Eyt6UHLuprFoA/1Jh5rxj9s61
    ssh_key_name: /home/hullet/.ssh/linode_ansible@blackfell.net.pub

timezone: Europe/London
locale: en_GB.UTF-8
keymap: uk

bb_group: haxxors

hostname: WOPR

###############################
####      Host Security & Remoting        ####
###############################

ssh_max_sessions: 7
ssh_max_auth_tries: 3
ssh_permit_root_login: "no"
ssh_permit_password_auth: "no"
ssh_allow_agent_forwarding: "no"
ssh_tcp_keep_alive: "yes"
ssh_use_dns: "no"
ssh_port: 22
mosh_port_range: 60000:60010

###############################
######         ARCH BASE TOOLS          #####
###############################

base_tools:
    - gcc
    - base
    - base-devel
    - binutils
    - make
    - automake
    - binutils
core_tools:
    - git
    - bash
    - zsh
    - bash-completion
    - less
    - bc
    - colordiff
    - rsync
    - sudo
    - polkit
    - ranger
    - vim
    - pkgfile
    - mlocate
    - lsof
    - htop
    - bashtop
    - ntp
    - cryptsetup
    - logrotate
    - lvm2
    - man-db
    - man-pages
    - vim
    - sysfsutils
    - sudo
    - networkmanager
    - openssh
    - python
    - python-pip
    - fontconfig
    - byobu
    - neofetch
    - rsync
    - sshfs
    - lolcat
    - cmatrix
    - cowsay
    - diff-so-fancy
    - vim-airline
    - vim-airline-themes
    - p7zip
core_networking:
    - net-tools
    - bind-tools
    - curl
    - wget
    - whois
    - inetutils
    - dhcp
    - netctl
    - openbsd-netcat
    - iputils
    - iw
    - openvpn
    - samba
    - traceroute
core_aur:
    - bash-pipes
    - oh-my-zsh-git
    - zsh-theme-powerlevel10k-git
    - ttf-meslo-nerd-font-powerlevel10k
    - vundle
    - gdb-multiarch
    - strace
    - pa-applet-git

###############################
####       Core Desktop Packages          ####
###############################

bb_gui_core:
  - xorg-server
  - xorg-xinit
  - xorg-xmodmap
  - xorg-xev
  - xorg-xbacklight
  - xorg-xrandr
  - xcape
  - xf86-video-intel
  - linux-lts
  - nvidia-lts
  - linux-lts-headers
  - opencl-nvidia
  - nvidia-prime
  - libvdpau
  - cuda
  - linux-firmware
  - texinfo
  - usbutils
  - alsa
  - pulseaudio
  - pavucontrol
  - lightdm
  - lightdm-slick-greeter
  - nitrogen
  - acpid
  - blueman
  - bluez-tools
  - open-vm-tools
  - xf86-video-vmware
  - xf86-input-vmmouse
  - mesa
  - lxappearance
  - thunar
  - jython
bb_gui_tools:
  - atom
  - firefox
  - lynx
  - flameshot
  - syncthing
  - mousepad
  - zathura
  - zathura-djvu
  - zathura-ps
  - zathura-pdf-poppler
  - vlc

###############################
######          i3 WM Packages            #####
###############################

bb_i3:
  - rxvt-unicode
  - rxvt-unicode-terminfo
  - xterm
  - pcmanfm
  - gtk3
  - conky
  - compton
  - i3-gaps
  - i3lock
  - xfce4-power-manager
  - rofi
  - papirus-icon-theme
  - noto-fonts
  - network-manager-applet
  - dunst
  - flameshot
  - firejail
  - firefox
bb_i3_aur:
  - termite
  #- pa-applet-git
  - siji-ttf
  - polybar
  - i3exit
  - pywal-git
  - clipit
  - matcha-gtk-theme
  - ttf-unifont
  - plymouth
  - linux-tools

###############################
######         Gnome Packages           #####
###############################

bb_gnome:
  - gnome
  - gnome-tweaks
  - latte-dock
bb_gnome_aur:
  - tela-circle-icon-theme-git
  - orchis-theme-git
  - arc-gtk-theme

###############################
######         Testing Packages           #####
###############################

current_blackarch_sha1sum: d062038042c5f141755ea39dbd615e6ff9e23121

bb_recon:
  - dnsrecon
  - blackarch/recon-ng
  - subfinder
  - dnsx
  - nmap
  - masscan
  - hping
  - fierce
  - waybackurls
  - assetfinder
  - amass
  - crackmapexec
  - wafw00f
  - blackarch/theharvester
bb_enum:
  - blackarch/wfuzz
  - blackarch/ffuf
  - blackarch/dirb
  - blackarch/gobuster
  - blackarch/enum4linux
  - blackarch/seclists
  - blackarch/meg
  - blackarch/rustscan
  - blackarch/wpscan
  - blackarch/netdiscover
  - nfs-utils
  - blackarch/kerbrute
  - blackarch/perl-image-exiftool
bb_vuln:
  - blackarch/exploitdb
  - blackarch/snmpcheck
  - blackarch/hydra
  - blackarch/nikto
  - blackarch/wpscan
  - blackarch/onesixtyone
  - blackarch/snmpcheck
  - net-snmp
  - blackarch/pwntools
  - blackarch/smbmap
bb_exploit:
  - blackarch/sqlmap
  - afl
  - afl-utils
  - blackarch/sulley
  - blackarch/metasploit
  - blackarch/empire
  - gdb
  - blackarch/gef
  - blackarch/pwndbg
  - blackarch/thc-ipv6
  - blackarch/smbexec
  - blackarch/android-apktool
  - blackarch/angr
  - blackarch/radare2
  - blackarch/frida
  - blackarch/dwarf
  - blackarch/binwalk
  - blackarch/checksec
bb_post:
  - linenum
  - powersploit
  - evil-winrm
  - pwncat-caleb
  - blackarch/windows-exploit-suggester 
  - blackarch/linux-exploit-suggester.sh
  - mariadb
  - blackarch/peass
  - blackarch/powersploit
  - blackarch/nishang
  - blackarch/bloodhound
  - blackarch/bloodhound-python
bb_general:
  - proxychains
  - curl
  - wget
  - scapy
  - docker
  - rust
  - go
  - go-tools
  - unfurl
  - blackarch/john
  - blackarch/hashcat
  - blackarch/hashcat-utils
  - dotnet-runtime
# Tools from Git  - Name and repo required.
bb_git:
  - name: "python_widgets"
    repo: "https://www.github.com/blackfell/python_widgets"
    add_git_dir_to_path: true
    install_command: "python -m pip install -r ./requirements.txt"
# Installing blackarch/gef instead now
#  - name: "peda_gef_pwndbg"
#    repo: "https://github.com/apogiatzis/gdb-peda-pwndbg-gef"
#    install_task: roles/testing_headless/tasks/peda_gef_pwndbg.yml #./install.sh  #Install too interactive, sorry
  - name: "snmpblow"
    repo: "https://github.com/grigorescu/snmpblow"
    add_git_dir_to_path: true
    install_command: "echo nothing"
  - name: "tomnomnom hacks"
    repo: "https://github.com/tomnomnom/hacks"
  - name: "john"
    repo: "https://github.com/openwall/john"
    add_git_dir_to_path: false    # Because it's in run, not in the git root
    install_command: "cd /opt/john/src && ./configure && make -s clean && make -sj$(nproc)"
  - name: "peass-ng"
    repo: "https://github.com/carlospolop/PEASS-ng"
  - name: "seatbelt"
    repo: "https://github.com/GhostPack/Seatbelt"
  - name: "windows CVEs 1"
    repo: "https://github.com/SecWiki/windows-kernel-exploits"

#TODO these?
#  - seatbelt
#  - kxss
#- LazyfuzZ
# TODO - Include SNMPBLOW?
# apt-get install tftpd-hpa
# mkdir /tftpboot && chmod 777 /tftpboot
# apt-get install libnet-snmp-perl libnet-rawip-perl
# wget http://www.willhackforsushi.com/sec660/snmpblow.pl
bb_rust:
  - feroxbuster
bb_go_get:
  - github.com/tomnomnom/gron
  - github.com/tomnomnom/httprobe
  - github.com/tomnomnom/gf

###############################
####       GUI   Testing Packages            ####
###############################

bb_gui_pentest:
  - blackarch/burpsuite
  - blackarch/zaproxy
  - firefox
  - blackarch/wireshark-cli
  - blackarch/wireshark-qt
  - termshark
  - blackarch/netdiscover
  - aircrack-ng
  - blackarch/wifite
  - blackarch/kismet
  - blackarch/macchanger
  - blackarch/ghidra
  - blackarch/r2ghidra
  - blackarch/ollydbg
  - blackarch/x64dbg
  - keepassxc
  - blackarch/veracrypt
  - pulseview
  - blackarch/winexe
  - blackarch/arduino
  - blackarch/gnuradio
  - blackarch/yersinia
  - blackarch/angr-management
  - jdk11-openjdk
  - libreoffice-still
bb_gui_pentest_aur:
  - rappel-git
  - saleae-logic2

#TODO - Add more tooling
# Pro tooling
# # Git tools
# gem install one_gadget
# Obsidian
#

###############################
####        OT   Testing Packages            ####
###############################

bb_ot:
  - git
  - perl
  - gem

bb_ot_aur:

# Tools from Git  - Name and repo required.
bb_ot_git:
  - name: "python_widgets"
    repo: "https://www.github.com/blackfell/python_widgets"
    add_git_dir_to_path: true
    install_command: "python -m pip install -r ./requirements.txt"
  - name: "snmpblow"
    repo: "https://github.com/grigorescu/snmpblow"
    add_git_dir_to_path: true
    install_command: "echo nothing"
  - name: "tomnomnom hacks"
    repo: "https://github.com/tomnomnom/hacks"
