" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1
" Airline config
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme = 'solarized'
set number
syntax on
set history=50
set ls=2
set showmode
set showcmd
set modeline
set ruler
set title
set nowrap
set linebreak
set showbreak=▹
set autoindent
set ignorecase
set smartcase
set gdefault
set hlsearch
set showmatch
set hidden
set backspace=eol,start,indent
set shiftwidth=4
set tabstop=4
set softtabstop=4
set shiftround
set expandtab
set nocompatible
filetype plugin on
set path+=**
set wildmenu
nmap <Leader>b :!echo <C-R><C-W> \| base64 -d<CR>
nmap <Leader>g :tabnew\|read !grep -Hnr '<C-R><C-W>'<CR>
nmap <Leader>s :%!sort -u --version-sort<CR>
nmap <Leader>W :w !sudo tee % > /dev/null

# easier split navigation with Ctrl - hjkl
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
set splitbelow
set splitright
