---
# Unfortunately go get is user based, so we just do the main user

- name: Custom tool installation commands
  shell:
    cmd: go install {{ item }}
  with_items: "{{ bb_go_get }}"
  become: yes
  become_user: "{{ bbvps_users.main_user.name }}"
