---

- name: Install Packages
  pacman: name={{ bb_gui_pentest }} state=present
  tags:
          - gui
          - pentest

- name: Install AUR tools
  shell: yay --noconfirm -S {{item}}
  with_items: "{{bb_gui_pentest_aur}}"
  when: bb_i3_aur is defined
  become: yes
  become_user: "{{bbvps_users.ansible_user.name}}"
  tags:
          - aur
