---
- name: Install oh my zsh for each user so they can customise later
  shell: "if [ ! -d ~/.oh-my-zsh/ ]; then echo -e 'y\n' | /usr/share/oh-my-zsh/tools/install.sh; fi"
  become: yes
  become_user: "{{ item.value.name }}"
  with_dict: "{{ bbvps_users }}"
  tags:
    - customisation

- name: Set global Zsh theme 2 - set theme for each user
  copy:
    src: ../files/.zshrc
    dest: /home/{{ item.value.name}}/.zshrc
    mode: 0744
  with_dict: "{{ bbvps_users }}"
  tags:
    - customisation

- name: Set p10k theme for each user
  copy:
    src: ../files/p10k.zsh
    dest: /home/{{ item.value.name}}/.p10k.zsh
    mode: 0744
  with_dict: "{{ bbvps_users }}"
  tags:
    - customisation

- name: Set root shell to ZSH too
  user:
    name: root
    shell: /bin/zsh
  tags:
    - customisation

- name: Configure oh my zsh for root
  shell: "if [ ! -d /root/.oh-my-zsh/ ]; then echo -e 'y\n' | /usr/share/oh-my-zsh/tools/install.sh; fi"
  become: yes
  become_user: root
  tags:
    - customisation

- name: Set global Zsh theme 4 - set theme for root as SPECIAL just cos
  copy:
    src: ../files/root.zshrc
    dest: /root/.zshrc
    owner: root
    group: root
    mode: 0744
    #become: yes
    #become_user: root
  tags:
    - customisation

- name: Global vimrc config - Changed to push a vimrc
  copy:
    src: vimrc
    dest: /etc/vimrc
    owner: root
    group: root
    mode: 0555

- name: Create Documents Directory for each user
  file:
    path: /home/{{ item.value.name }}/Documents
    state: directory
    mode: '0755'
    owner: "{{ item.value.name }}"
    group: "{{ item.value.group }}"
  with_dict: "{{ bbvps_users }}"
  become: true
  tags:
    - customisation

- name: Create Downloads Directory for each user
  file:
    path: /home/{{ item.value.name }}/Downloads
    state: directory
    mode: '0755'
    owner: "{{ item.value.name }}"
    group: "{{ item.value.group }}"
  with_dict: "{{ bbvps_users }}"
  become: true
  tags:
    - customisation

- name: Create Pictures Directory for each user
  file:
    path: /home/{{ item.value.name }}/Pictures
    state: directory
    mode: '0755'
    owner: "{{ item.value.name }}"
    group: "{{ item.value.group }}"
  with_dict: "{{ bbvps_users }}"
  become: true
  tags:
    - customisation

- name: Create Screenshots Directory for each user
  file:
    path: /home/{{ item.value.name }}/Pictures/screenshots
    state: directory
    mode: '0755'
    owner: "{{ item.value.name }}"
    group: "{{ item.value.group }}"
  with_dict: "{{ bbvps_users }}"
  become: true
  tags:
    - customisation
