---
- name: Install core gui utils & drivers
  pacman: name={{ bb_gui_core }} state=present
  tags:
          - gui


- name: Install gui tools
  pacman: name={{ bb_gui_tools }} state=present
  tags:
          - gui
          - tools

- name: Create backgrounds directory if not existing
  file:
    path: "/usr/share/backgrounds"
    state: directory
    mode: '0775'
    owner: root
    group: root
  become: true

- name: Put desktop background in right spot
  copy:
    src: BFBackground.png
    dest: /usr/share/backgrounds/BFBackground.png
  tags:
    - gui

- name: Configure Boot - DM and Grub
  include: boot_config.yml

- name: Configure Fonts for Powerline
  include: powerline_fonts.yml

- name: Enable ACPI, NetworkManager vmtools & Bluetooth Services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - acpid
    - bluetooth
    - NetworkManager
    - vmtoolsd
    - vmware-vmblock-fuse

- name: Create Firefox Profile Directory
  file:
    path: "/home/{{item.value.name}}/.mozilla/firefox/Testing"
    state: directory
    mode: '0700'
    owner: "{{item.value.name}}"
    group: "{{item.value.group}}"
  become: true
  with_dict: "{{ bbvps_users }}"

- name: Install Gnome
  include: gnome.yml

- name: Install and configure i3 WM
  include: i3.yml
