---
- name: Install core gui utils & drivers
  pacman: name={{ bb_gui_core }} state=present
  tags:
          - gui


- name: Install gui tools
  pacman: name={{ bb_gui_tools }} state=present
  tags:
          - gui
          - tools

# TODO - separate per-DE?
- name: Set gtk-2 theme
  copy:
          src: gtkrc-2.0
          dest: /usr/share/gtk-2.0/
  tags:
          - gui

- name: Set gtk-3 theme
  copy:
          src: settings.ini
          dest: /usr/share/gtk-3.0/
  tags:
          - gui

- name: Create backgrounds directory if not existing
  file:
    path: "/usr/share/backgrounds"
    state: directory
    mode: '0775'
    owner: root
    group: root
  become: true

- name: Put desktop background in right spot
  copy:
    src: BFBackground.png
    dest: /usr/share/backgrounds/BFBackground.png
  tags:
    - gui

- name: Configure Boot - DM and Grub
  include: boot_config.yml

- name: Configure Fonts for Powerline
  include: powerline_fonts.yml

- name: Enable ACPI, NetworkManager & Bluetooth Services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - acpid
    - bluetooth
    - NetworkManager

- include: i3.yml
